"""
File: src/agent/state.py
Task: Defines the AgentState schema, which acts as the shared 'short-term memory' 
for the LangGraph workflow. It stores user inputs, the active DataFrame, 
planning decisions, tool execution outputs, and tracks error history 
to enable autonomous self-correction loops.
"""

from __future__ import annotations
from typing import TypedDict, List, Dict, Any, Optional
import pandas as pd

class AgentState(TypedDict, total=False):
    # Inputs
    # Initial data provided by the user to start the process
    question: str
    csv_path: str

    # Runtime only
    # Objects instantiated and maintained during the graph execution
    df: pd.DataFrame

    # ==========================================
    # Loop Control & Memory: track execution cycles and errors
    # ==========================================
    retry_count: int       # Tracks current retry attempts to prevent infinite loops
    error_log: List[str]   # List of error messages for the Planner to review and adjust strategies

    # Planner output
    # Decisions and roadmaps generated by the LLM Planner
    plan: List[str]
    plan_tools: List[str]  # Machine-readable list of tools identified from the plan lines
    target: Optional[str]
    target_selection: Dict[str, Any]
    target_rerank: Dict[str, Any]

    # Tool output
    # Results and metadata gathered from analysis tools and profiling
    tool_result: Dict[str, Any]

    # Final output
    # The final natural language response presented to the user
    final_answer: str